server:
  port: 4050

spring:
  rabbitmq:
    host: 192.169.0.147
    port: 5672
    username: pig
    password: 123456

sms:
  aliyun:
    accessKey: accessKey
    secretKey: secretKey
    channels:
      loginCodeChannel: SMS_34630023