server:
  port: 5003

# datasoure默认使用JDBC
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.147:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    
zipkin:
  collector:
    rabbitmq:
      addresses: 192.168.0.147:5672
      password: 123456
      username: pig
      queue: zipkin
  storage:
    type: mysql